name: CI

on:
  push:    
  pull_request:    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]        
        ocaml-compiler:
          - 4.11.2
          - 4.12.1          
          - 4.13.1
          - 4.12.0+domains

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ocaml-variants.${{ matrix.ocaml-compiler }}
          opam-repositories: |
            multicore: https://github.com/ocaml-multicore/multicore-opam.git
            default: https://github.com/ocaml/opam-repository.git

      - run: opam install . --deps-only

      - run: opam exec -- dune b @all

      - run: opam exec -- dune runtest
